### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by yrrah** [olir/gephi-neo4j-url-importer-plugin#1]
**Describe the bug**
Unable to connect to local Neo4j database

**To Reproduce**
1. Attempt to import database with default settings
2. Click on 'Test Connection'
3. See error "Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database."

**Expected behavior**
Should see message "Connection successful!"

**Desktop**
 - OS: Ubuntu 18.04.4 LTS
 - Gephi: 0.9.2 201709241107 w/ Java: 1.8.0_231
 - neo4j: 4.0.4 w/ Java: 11.0.7

**Additional context**
I was able to resolve this by compiling with the 4.0.1 org.neo4j.driver. 

I will update with my changes, but need to clean them up. I spent quite awhile trying to find the RELEASE82 version of Netbeans dependencies and eventually got them manually from here 
https://maven.scijava.org/content/repositories/public/org/netbeans/api/

Thanks for this plugin!

**Comment by olir** [comment]
hi. if you have any addional comments, feel free to reopen the issue.

**Comment by nrouyer** [comment]
Hi, same issue.
If we don't recompile, there is no way to make the release archive work, that's it?
